<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>netstandard2.1</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <LangVersion>default</LangVersion>
        
        <!-- NuGet Metadata -->
        <PackageId>Berdsk.Sdk.SuperFrete</PackageId>
        <AssemblyName>Berdsk.Sdk.SuperFrete</AssemblyName>
        <RootNamespace>Berdsk.Sdk.SuperFrete</RootNamespace>
        <Title>Berdsk.Sdk.SuperFrete</Title>
        <Authors>Berdsk</Authors>
        <Company>Berdsk</Company>
        <Description>Biblioteca não oficial para integração com a API da SuperFrete. Simplifique o cálculo de frete e gestão de envios em sua aplicação .NET.</Description>
        <PackageTags>superfrete;frete;correios;envios;logistica;berdsk;sdk</PackageTags>
        <PackageProjectUrl>https://berdsk.com.br</PackageProjectUrl>
        <PackageIcon>berdsk-icon.png</PackageIcon>
        <PackageReadmeFile>README.md</PackageReadmeFile>
        <PackageLicenseExpression>MIT</PackageLicenseExpression>
        <RepositoryUrl>https://github.com/berdsk/Berdsk.Sdk.SuperFrete</RepositoryUrl>
        <RepositoryType>git</RepositoryType>
        
        <!-- Versioning will be handled by GitVersion in the workflow, 
             but we can set a base version here if needed -->
        <Version>1.0.0</Version>
    </PropertyGroup>

    <ItemGroup>
        <None Include="resources\berdsk-icon.png" Pack="true" PackagePath="\" />
        <None Include="README.md" Pack="true" PackagePath="\" />
    </ItemGroup>

    <ItemGroup>
        <PackageReference Include="System.Text.Json" Version="8.0.5" />
    </ItemGroup>

</Project>
